### ISSUE TITLE
Arjun Jadhav After Restore Data import not work 

### ISSUE THREAD

**Issue by milindbhoye** [BimaMitra/Ultimate#7] opened 2019-02-01 07:42 UTC

**Comment by milindbhoye** [comment] 2019-02-01 07:43
Data Received Assign to Sir

**Comment by DeepakJalan** [comment] 2019-02-01 07:47
Data Corrected & Sent to client. Please close the issue once the problem is solved.

**Comment by milindbhoye** [comment] 2019-02-01 08:46
Data Solve All Function Work

**Closed as completed** 2019-02-01 08:51 UTC
Labels: bug
